### PR TITLE
Tooltip

### PR DESCRIPTION
**Pull request by swedishfrenchpress**
Issue #40. 
I worked on some tool tip designs that will work on both light and dark mode. I modified the existing [material design info icon](https://material.io/resources/icons/?icon=restore_page&style=baseline) into a filled and outline version. The tool tip is a simple rectangle with a 3px rounded radius corners connected with a triangle. I'll included all the icons and tool tip bubbles in the export folder of my pull request. I hope this helps, open to any suggestions!
Group 3
Group 4

### CODE REVIEW

**Review by diogorsergio — APPROVED** [review]
Looks good from a design perspective.

**Review by ShahanaFarooqui — APPROVED** [review]
Thanks. Should we use filled version or outlined version of the tooltip in the project? Or both versions will be used depending upon the type of the information?

**Comment by swedishfrenchpress** [comment]
@ShahanaFarooqui I recommend using the outlined version for light mode and the filled version for dark mode. I think they offer the best contrast.

**Comment by ShahanaFarooqui** [comment]
Love it. Cannot wait to work on it :D. It will be great if we can add some animations also on the website.

**Comment by swedishfrenchpress** [comment]
> Love it. Cannot wait to work on it :D. It will be great if we can add some animations also on the website.

Thanks! I think adding some animation would help take the landing page the next level! Would love to work with you on that.

I'm not sure why the website template issue is showing in this pull request / issue. Still learning my way around github.

**Comment by ShahanaFarooqui** [comment]
The better approach to manage different issues is:

1: Create a new branch from `Design` branch for each issue, eg branch name `website-template'.
2: Publish the branch.
3: Commit all the changes into that newly created branch.
4:  Open a new PR to merge final changes into `Design` branch.

However, we have another private repository for the website. I just sent you the memeber request for the same. Please feel free to accept and push your changes into that repo.

**Comment by diogorsergio** [comment]
@swedishfrenchpress Awesome work! Don't stress about it. I think the issue might be because you didn't create branches for the work separate issues, so its all on the same PR from your design branch.

Ideally you could start your workflow like this: 
1. git checkout design -> Changes branch to Design
2. git  checkout -b **ux/website** design -> The `-b` creates a new branch named **ux/website** , based of the Design branch. 
3. Work on the design and add the file/folders.
4. git add -A -> Adds all the files to the commit.
5. git commit -m '[UX] - Website"  -> Gives a message to the commit. 
6. git push -u origin **ux/website** -> Pushes the branch  and gives you the link to the PR.

If you are working on multiple features, like you were now with the Tooltip and Website. You need to create a branch for each feature e.g. **ux/tooltip** and **ux/website**. 

Then when you want to work on one of them you just do: 
1. git  checkout **ux/tooltip** -> You don't need the `-b` here because you already created the branch. So you just change to the **ux/tooltip** created the previous step with `git checkout <branch name>`.
2. Work on the design and add the file/folders for that branch.
3. git add -A -> Adds all the files to the commit.
4. git commit -m '[UX] - Tooltip "  -> Gives a message to the commit. 
5. git push -u origin **ux/tooltip** -> Pushes the branch  and gives you the link to the PR.

Hope this helps! :) It's a learning curve at the beginning, but it will become more easy as you do it. Just keep in mind if you are working on separate issues you need to keep the design separated by branches, and then you add, commit, and push on those branches individually.

**Pull request closed without merging**
