### PR TITLE
Ux/loginpage

### PR DESCRIPTION
**Pull request by swedishfrenchpress**
RTL login page
Issue #58

### CODE REVIEW

**Comment by saubyk** [comment]
@swedishfrenchpress @diogorsergio 
Can we adjust this to the attached?
Screen Shot 2021-02-20 at 1 06 50 PM

**Comment by swedishfrenchpress** [comment]
@saubyk I love it! I updated the source and export files to better match the mockup. Is there anything else I can do to help resolve issue?

**Comment by diogorsergio** [comment]
Looking good from my side too! Thanks the awesome work @swedishfrenchpress. Just figuring something out with Github before merging the request.

**Review by diogorsergio — APPROVED** [review]
Perfect! Again, thanks a lot for the work.

**Pull request merged**
