### PR TITLE
[UX] - Onboarding Setup

### PR DESCRIPTION
**Pull request by diogorsergio**
Initial onboarding setup to configure RTL, will guide users through the flow and maybe give an explanation of what's needed and why?

Should be contextual and adapt to the user choices, e.g. requirements should be tailored based on the selected implementation.

At the moment keeping this for essential options only for RTL to start.

Could include costumization questions e.g.: Dashboard layout, Fiat currency, Theme, but at this point user haven't seen or interacted with the UI, so it lacks context and the user might not know what options serve him best withouth proper usage. 

Thoughts?

### CODE REVIEW

**Comment by diogorsergio** [comment]
> Missing critical 'lnServerUrl' information.

Added that step and separated flows so they can be contextual to the choosen implementation.
Should we also ask for swap server? as an optional step?

**Comment by ShahanaFarooqui** [comment]
@diogorsergio adding swapServerUrl seems like a logical step as we are supporting loop in/out.

**Comment by diogorsergio** [comment]
> @diogorsergio adding swapServerUrl seems like a logical step as we are supporting loop in/out.

Added the Swap Server flow step and fixed a mistake by removing the browse button in the lnServerUrl step.

**Comment by diogorsergio** [comment]
Removed Swap Server step form the CLT flow and the browse functionality. Since we removed the browse funcionality we should have checks and validation that the user input is valid when "Next" is pressed.

**Pull request merged**
